package modules.saveboard.view;

import core.model.chesspieces.Pesa;
import core.view.CellDrawable;
import core.view.ChessBoardPanel;
import java.awt.event.ActionListener;
import javax.swing.event.ChangeListener;
import modules.saveboard.model.BoardDefinition;

/**
 *
 * @author Bernat Galmés Rubert
 */
public class MainWindow extends javax.swing.JFrame {

    private final ChessBoardPanel tauler;
    private final BoardDefinition model;

    public MainWindow(BoardDefinition model) {
        this.model = model;
        initComponents();
        tauler = (ChessBoardPanel) T;
    }

    public void attachActionLister(ActionListener actionListener) {
        this.btn_addPiece.setActionCommand("addPiece");
        this.btn_addPiece.addActionListener(actionListener);

        this.btn_compute.setActionCommand("compute");
        this.btn_compute.addActionListener(actionListener);

        this.btn_resetPieces.setActionCommand("resetPieces");
        this.btn_resetPieces.addActionListener(actionListener);
    }

    public void attachChangeListener(ChangeListener changeListener) {
        this.sp_boardSize.addChangeListener(changeListener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        T = new core.view.ChessBoardPanel(BoardDefinition.INI_BOARD_SIZE);
        panel_options = new javax.swing.JPanel();
        sp_boardSize = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        lb_boardSize = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lst_piecesBoard = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        cb_selectPiece = new javax.swing.JComboBox(BoardDefinition.T_PECES) ;
        btn_addPiece = new javax.swing.JButton();
        btn_resetPieces = new javax.swing.JButton();
        btn_compute = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess");
        setAlwaysOnTop(true);
        setResizable(false);

        T.setPreferredSize(new java.awt.Dimension(500, 500));

        javax.swing.GroupLayout TLayout = new javax.swing.GroupLayout(T);
        T.setLayout(TLayout);
        TLayout.setHorizontalGroup(
            TLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 601, Short.MAX_VALUE)
        );
        TLayout.setVerticalGroup(
            TLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 634, Short.MAX_VALUE)
        );

        sp_boardSize.setModel(new javax.swing.SpinnerNumberModel(8, 3, 20, 1));

        jLabel2.setText("Select board size:");

        lb_boardSize.setText("Board_size");

        javax.swing.GroupLayout panel_optionsLayout = new javax.swing.GroupLayout(panel_options);
        panel_options.setLayout(panel_optionsLayout);
        panel_optionsLayout.setHorizontalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_optionsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lb_boardSize)
                    .addComponent(sp_boardSize, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(426, 426, 426))
        );
        panel_optionsLayout.setVerticalGroup(
            panel_optionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_optionsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sp_boardSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_boardSize)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(lst_piecesBoard);

        jLabel3.setText("Pieces selected:");

        btn_addPiece.setText("Add a piece");

        btn_resetPieces.setBackground(new java.awt.Color(223, 89, 95));
        btn_resetPieces.setText("Clean pieces");

        btn_compute.setBackground(new java.awt.Color(19, 16, 200));
        btn_compute.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btn_compute.setForeground(new java.awt.Color(242, 242, 242));
        btn_compute.setText("Compute");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cb_selectPiece, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(btn_addPiece))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_compute, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_resetPieces, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_selectPiece, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addPiece))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_resetPieces)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_compute)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel_options, javax.swing.GroupLayout.PREFERRED_SIZE, 259, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_options, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel T;
    javax.swing.JButton btn_addPiece;
    javax.swing.JButton btn_compute;
    javax.swing.JButton btn_resetPieces;
    private javax.swing.JComboBox<String> cb_selectPiece;
    javax.swing.JLabel jLabel2;
    javax.swing.JLabel jLabel3;
    javax.swing.JMenu jMenu1;
    javax.swing.JMenu jMenu2;
    javax.swing.JMenuBar jMenuBar1;
    javax.swing.JPanel jPanel1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JLabel lb_boardSize;
    javax.swing.JList lst_piecesBoard;
    javax.swing.JPanel panel_options;
    javax.swing.JSpinner sp_boardSize;
    // End of variables declaration//GEN-END:variables

    public void updateView() {
        if (model.getBoardSize() != tauler.getN()) {
            tauler.changeSize(model.getBoardSize());
            lb_boardSize.setText("Board_size: " + model.getBoardSize());
        }

        this.lst_piecesBoard.setListData(this.model.getPieces().toArray());

    }

    public void colocaPeces(CellDrawable[][] pecesColocades) {
        for (int iFila = 0; iFila < pecesColocades.length; iFila++) {
            CellDrawable[] fila = pecesColocades[iFila];
            for (int iColumna = 0; iColumna < fila.length; iColumna++) {
                CellDrawable pesa = fila[iColumna];
                if (pesa != null) {
                    tauler.colocarPesa(iFila, iColumna, pesa);
                }
            }
        }
    }

    public void reset() {
        tauler.resetBoard();
    }

    public String getCurrentPiezeSelected() {
        return (String) cb_selectPiece.getSelectedItem();
    }

}
